### PR TITLE
added fix for 64bit installer, variable file updated.

### PR DESCRIPTION
**Pull request by radhikabhat08**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3)

### CODE REVIEW

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3)* status: all files reviewed, 3 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[variables.tf, line 6 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSixVi01Zc4uCtWRWE5:-MSixVi01Zc4uCtWRWE6:b7xet2i) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/7f3068c6dadb08e236d954298e5868d849f81b01/variables.tf#L6)):*
> ```HCL
>   description = "Number of instances to create."
>   type        = number
>   default     = 1
> ```

Why are we removing this default?
___
*[variables.tf, line 12 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSixG7-E8Uw5rR7lJN2:-MSixG7-E8Uw5rR7lJN3:b-1n3gi8) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/7f3068c6dadb08e236d954298e5868d849f81b01/variables.tf#L12)):*
> ```HCL
>   description = "The Azure Virtual Machine SKU."
>   type        = string
>   default     = "Standard_DS1_v2"
> ```

Why are we removing a number of default values?  This, in particular, gives the user an idea of the instance size needed.
___
*[examples/run-stc-gui/variable.tf, line 57 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSixwMVExs6LtNwCX2T:-MSixwMVExs6LtNwCX2U:b-7zb27f) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/725fc85040d0974390680bbf164814c7a2d038c1/examples/run-stc-gui/variable.tf#L57)):*
> ```HCL
>   description = "File path to 'Spirent TestCenter Application x64.exe' or 'Spirent TestCenter Application.exe' installer."
>   type        = string
>   default     = "../../../stcv-Ninstances/install-files/Spirent TestCenter Application.exe" 
> ```

Remove `default` value?  On the AWS side, we don't have a default.  If we want a default, it should be relative to current directory.
https://github.com/Spirent-Terraform-Modules/terraform-aws-stc-gui/blob/main/variables.tf#L77-L88

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3)* status: all files reviewed, 4 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[variables.tf, line 6 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSixVi01Zc4uCtWRWE5:-MSj5-cu511ryCIHRLEn:buhdncq) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/7f3068c6dadb08e236d954298e5868d849f81b01/variables.tf#L6)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Why are we removing this default?
</blockquote></details>

Default to 1 is probably good.
___
*[examples/run-stc-gui/main.tf, line 30 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSj5ECS1a8b-XS4ZsuA:-MSj5ECS1a8b-XS4ZsuB:bwvesfl) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/725fc85040d0974390680bbf164814c7a2d038c1/examples/run-stc-gui/main.tf#L30)):*
> ```HCL
> output "instance_public_ips" {
>   value = module.stc_gui.*.instance_public_ips
> }
> ```

Not really an error but  you can get rid of circle here if you add an extra line at the end of the file.

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3)* status: all files reviewed, 5 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[variables.tf, line 27 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSjaVU25dXC79v96wvD:-MSjaVU3-XG-g_PGx0NC:bas5vbc) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/725fc85040d0974390680bbf164814c7a2d038c1/variables.tf#L27)):*
> ```HCL
>   description = "Resource group name in Azure."
>   type        = string
>   default     = ""
> ```

Maybe this should be removed instead of empty string?  I think  "default" is just a name and may not be there.  Removal would be consistent with vnet module.  https://github.com/Azure/terraform-azurerm-vnet/blob/master/variables.tf

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3)* status: all files reviewed, 5 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[variables.tf, line 27 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSjaVU25dXC79v96wvD:-MSjfn1bBEBQZG0CkMra:bwb8qio) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/725fc85040d0974390680bbf164814c7a2d038c1/variables.tf#L27)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Maybe this should be removed instead of empty string?  I think  "default" is just a name and may not be there.  Removal would be consistent with vnet module.  https://github.com/Azure/terraform-azurerm-vnet/blob/master/variables.tf
</blockquote></details>

Sorry, just the default not the variable.

**Review by radhikabhat08 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @rmyers808)

___
*[variables.tf, line 6 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSixVi01Zc4uCtWRWE5:-MSlOyqc7D4zPa1gW1jO:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/7f3068c6dadb08e236d954298e5868d849f81b01/variables.tf#L6)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Default to 1 is probably good.
</blockquote></details>

Done.
___
*[variables.tf, line 12 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSixG7-E8Uw5rR7lJN2:-MSlOy6n8kIjIl8habn1:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/7f3068c6dadb08e236d954298e5868d849f81b01/variables.tf#L12)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Why are we removing a number of default values?  This, in particular, gives the user an idea of the instance size needed.
</blockquote></details>

Done.
___
*[variables.tf, line 27 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSjaVU25dXC79v96wvD:-MSlOuJS3cnbAamKt06y:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/725fc85040d0974390680bbf164814c7a2d038c1/variables.tf#L27)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Sorry, just the default not the variable.
</blockquote></details>

Done.
___
*[examples/run-stc-gui/main.tf, line 30 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSj5ECS1a8b-XS4ZsuA:-MSlOt-WEt6RfhuBQp7R:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/725fc85040d0974390680bbf164814c7a2d038c1/examples/run-stc-gui/main.tf#L30)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Not really an error but  you can get rid of circle here if you add an extra line at the end of the file.
</blockquote></details>

Done.
___
*[examples/run-stc-gui/variable.tf, line 57 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-MSixwMVExs6LtNwCX2T:-MSlOrrfEkdbcqbCbD9x:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/725fc85040d0974390680bbf164814c7a2d038c1/examples/run-stc-gui/variable.tf#L57)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Remove `default` value?  On the AWS side, we don't have a default.  If we want a default, it should be relative to current directory.
https://github.com/Spirent-Terraform-Modules/terraform-aws-stc-gui/blob/main/variables.tf#L77-L88
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-:-MSnbRfx34mLa4MklubS:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ltran-spirent and @rmyers808)

**Review by rmyers808 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/3#-:-MSnqv8PCGM4cQQyWmnw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltran-spirent and @rmyers808)

**Pull request merged**
