### PR TITLE
added new tf files for stcgui deployment

### PR DESCRIPTION
**Pull request by radhikabhat08**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1)

### CODE REVIEW

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1)* status: all files reviewed, 1 unresolved discussion (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[README.md, line 1 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1#-MRqUaeT8fCIf84En0aE:-MRqUaeT8fCIf84En0aF:bguj3r7) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/b3db03f7f833c33784e34f236ee04814667883c4/README.md#L1)):*
> ```Markdown
> # DOCUMENTATIONRun STCv traffic generator instances with public and test networks.Instances can be controlled by the Spirent TestCenter application.## Requirements
> ```

There are too many things on this line.  Need to add some newlines.

**Review by radhikabhat08 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @jhiga, @ltran-spirent, and @rmyers808)

___
*[README.md, line 1 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1#-MRqUaeT8fCIf84En0aE:-MS2GX4CEaBzwVGyv71w:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/b3db03f7f833c33784e34f236ee04814667883c4/README.md#L1)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

There are too many things on this line.  Need to add some newlines.
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1#-:-MS4BqOF4sjNgm9xA7Ny:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltran-spirent and @rmyers808)

**Review by rmyers808 — APPROVED** [review]
> Reviewed 3 of 10 files at r1, 3 of 6 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltran-spirent)

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1)* status: all files reviewed, 1 unresolved discussion (waiting on @ltran-spirent and @radhikabhat08)

___
*[variables.tf, line 64 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1#-MS9mL-i1QKHnxH3onGq:-MS9mL-i1QKHnxH3onGr:b-e0zegl) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/9062b4770729954f810367a962bf668a8da6dd32/variables.tf#L64)):*
> ```HCL
> variable "src_dir" {
>   description = "Source directory containing 'Spirent TestCenter Application.exe'.  This directory will be copied to each instance."
>   type        = string
> ```

I think you can check this in AS-IS.  But,  I think it's safer to just  specify STC installer since depends come for HTTP download.  See terraform-aws-stc-gui in  my latest review.  It's easier to validate the variable and avoids issues with user specifying a dir that contains lot of  unnecessary files.

**Review by rmyers808 — COMMENTED** [review]
lgtm

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1#-:-MS9o7EKD2yF_xILbBX2:bb7k0qh)* status: all files reviewed, 1 unresolved discussion (waiting on @ltran-spirent and @radhikabhat08)

**Review by rmyers808 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1#-:-MS9oB0P349yE2jB53Wd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltran-spirent and @radhikabhat08)

**Review by used-to-work — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1#-:-MSC8DfW0B89v8b7v5XB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @radhikabhat08)

**Review by radhikabhat08 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @jhiga and @rmyers808)

___
*[variables.tf, line 64 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stc-gui/1#-MS9mL-i1QKHnxH3onGq:-MSCcDHcBuuFE0ELDOJx:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stc-gui/blob/9062b4770729954f810367a962bf668a8da6dd32/variables.tf#L64)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

I think you can check this in AS-IS.  But,  I think it's safer to just  specify STC installer since depends come for HTTP download.  See terraform-aws-stc-gui in  my latest review.  It's easier to validate the variable and avoids issues with user specifying a dir that contains lot of  unnecessary files.
</blockquote></details>

Done.

**Pull request merged**
